<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllUsers()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u');

        return $qb->getQuery()
                  ->getResult();
    }
}
